import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, BarChart3, Bell, ChevronDown, CircleGauge, FileClock, Menu, Search, Settings, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";

const nav = [
  { label: "Overview", to: "/", icon: CircleGauge }, { label: "Recovery Cases", to: "/recovery-cases", icon: Activity },
  { label: "Approvals", to: "/approvals", icon: ShieldCheck, count: 3 }, { label: "Analytics", to: "/analytics", icon: BarChart3 },
  { label: "Audit Replay", to: "/audit-replay", icon: FileClock }, { label: "Settings", to: "/settings", icon: Settings },
] as const;

function Sidebar({ close }: { close?: () => void }) {
  return <div className="flex h-full flex-col bg-sidebar px-4 py-5"><div className="flex h-12 items-center gap-3 px-2"><div className="grid size-8 place-items-center rounded-lg border border-primary/30 bg-primary-soft shadow-[0_0_24px_var(--primary-glow)]"><Activity className="size-4 text-primary" /></div><div><p className="text-[11px] font-bold tracking-[0.16em] text-foreground">MANDATE DOCTOR</p><p className="mt-0.5 text-[10px] text-muted-foreground">Revenue recovery OS</p></div>{close && <Button variant="ghost" className="ml-auto size-10 p-0" onClick={close} aria-label="Close navigation"><X className="size-4"/></Button>}</div><nav className="mt-8 space-y-1">{nav.map((item) => <Link key={item.label} to={item.to} activeOptions={{ exact: item.to === "/" }} onClick={close} activeProps={{ className: "!bg-sidebar-accent !text-foreground before:opacity-100" }} className="relative flex h-11 items-center gap-3 rounded-lg px-3 text-sm font-medium text-muted-foreground transition-colors before:absolute before:left-0 before:h-5 before:w-0.5 before:rounded-full before:bg-primary before:opacity-0 hover:bg-sidebar-accent/60 hover:text-foreground"><item.icon className="size-4"/><span>{item.label}</span>{item.count && <span className="ml-auto rounded-full bg-warning-soft px-2 py-0.5 text-[10px] text-warning">{item.count}</span>}</Link>)}</nav><div className="mt-auto rounded-xl border border-border bg-background/40 p-4"><div className="flex items-center gap-2"><Sparkles className="size-4 text-ai"/><span className="text-xs font-semibold text-foreground">Decision discipline</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">The AI proposes.<br/><span className="text-foreground">The Policy Engine decides.</span></p></div></div>;
}

export function AppShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const pathname = useRouterState({ select: (s) => s.location.pathname });
  const title = nav.find((item) => item.to === pathname)?.label ?? (pathname.startsWith("/recovery-cases/") ? "Case Replay" : "Mandate Doctor");
  return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-border lg:block"><Sidebar/></aside>{open && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-overlay" onClick={() => setOpen(false)} aria-label="Close navigation overlay"/><aside className="relative h-full w-72 border-r border-border"><Sidebar close={() => setOpen(false)}/></aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 h-16 border-b border-border bg-background/80 backdrop-blur-xl"><div className="flex h-full items-center gap-3 px-4 sm:px-6 lg:px-8"><Button variant="ghost" className="size-10 p-0 lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu className="size-5"/></Button><p className="hidden text-sm font-medium text-muted-foreground sm:block">{title}</p><div className="relative ml-auto hidden w-full max-w-xs md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input className="h-9 w-full rounded-lg border border-border bg-secondary/60 pl-9 pr-14 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary/50 focus:ring-2 focus:ring-primary/10" placeholder="Search cases..."/><kbd className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[10px] text-muted-foreground">⌘ K</kbd></div><Badge status="Test">TEST MODE</Badge><Button variant="ghost" className="relative size-10 p-0" aria-label="Notifications"><Bell className="size-4"/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-danger"/></Button><button className="flex items-center gap-2 rounded-lg p-1.5 hover:bg-accent" aria-label="Open profile menu"><span className="grid size-7 place-items-center rounded-md bg-primary-soft text-xs font-semibold text-primary">RK</span><ChevronDown className="size-3 text-muted-foreground"/></button></div></header><main className="mx-auto min-h-[calc(100vh-4rem)] max-w-[1600px] p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
