/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditReplayRouteImport } from './routes/audit-replay'
import { Route as RecoveryCasesRouteImport } from './routes/recovery-cases'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecoveryCasesIndexRouteImport } from './routes/recovery-cases.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditReplayRoute = AuditReplayRouteImport.update({
  id: '/audit-replay',
  path: '/audit-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCasesRoute = RecoveryCasesRouteImport.update({
  id: '/recovery-cases',
  path: '/recovery-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCasesIndexRoute = RecoveryCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecoveryCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-replay': typeof AuditReplayRoute
  '/recovery-cases': typeof RecoveryCasesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/recovery-cases/': typeof RecoveryCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-replay': typeof AuditReplayRoute
  '/settings': typeof SettingsRoute
  '/recovery-cases': typeof RecoveryCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-replay': typeof AuditReplayRoute
  '/recovery-cases': typeof RecoveryCasesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/recovery-cases/': typeof RecoveryCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-replay'
    | '/recovery-cases'
    | '/settings'
    | '/recovery-cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-replay'
    | '/settings'
    | '/recovery-cases'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-replay'
    | '/recovery-cases'
    | '/settings'
    | '/recovery-cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditReplayRoute: typeof AuditReplayRoute
  RecoveryCasesRoute: typeof RecoveryCasesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-replay': {
      id: '/audit-replay'
      path: '/audit-replay'
      fullPath: '/audit-replay'
      preLoaderRoute: typeof AuditReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-cases': {
      id: '/recovery-cases'
      path: '/recovery-cases'
      fullPath: '/recovery-cases'
      preLoaderRoute: typeof RecoveryCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-cases/': {
      id: '/recovery-cases/'
      path: '/'
      fullPath: '/recovery-cases/'
      preLoaderRoute: typeof RecoveryCasesIndexRouteImport
      parentRoute: typeof RecoveryCasesRoute
    }
  }
}

interface RecoveryCasesRouteChildren {
  RecoveryCasesIndexRoute: typeof RecoveryCasesIndexRoute
}

const RecoveryCasesRouteChildren: RecoveryCasesRouteChildren = {
  RecoveryCasesIndexRoute: RecoveryCasesIndexRoute,
}

const RecoveryCasesRouteWithChildren = RecoveryCasesRoute._addFileChildren(
  RecoveryCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditReplayRoute: AuditReplayRoute,
  RecoveryCasesRoute: RecoveryCasesRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
